### ISSUE TITLE
lastest iso (24H2) unsupported?

### ISSUE THREAD

**Issue by doums** [ntdevlabs/tiny11builder#263]
Hi, I successfully built the image via `tiny11Coremaker.ps1` script from `Win11_24H2_French_x64.iso`. 
But when trying to install it on a vm, after disk partitioning, the installation process fails at 10% "Windows installation has failed".

**Comment by spd-asia** [comment]
The script is trying to directly access the mounted registry hives through the `.NET Registry API ([Microsoft.Win32.Registry])`, but from my experience this API doesn't work well with mounted registry hives that use the "z" prefix.

**Comment by Karl-WE** [comment]
adding to @doums 
it begins for me with 
`Copy-Item: E:\tiny11\tiny11maker.ps1:220
Line |
 220 |  Copy-Item -Path "$PSScriptRoot\autounattend.xml" -Destination "$Scrat …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path 'E:\tiny11\autounattend.xml' because it does not exist.`

**Comment by Karl-WE** [comment]
```
**********************
PowerShell transcript start
Start time: 20241106222002
Username: WS2025\Administrator
RunAs User: WS2025\Administrator
Configuration Name: 
Machine: WS2025 (Microsoft Windows NT 10.0.26311.0)
Host Application: C:\Program Files\PowerShell\7\pwsh.dll
Process ID: 19756
PSVersion: 7.4.6
PSEdition: Core
GitCommitId: 7.4.6
OS: Microsoft Windows 10.0.26311
Platform: Win32NT
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1, 6.0, 7.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
WSManStackVersion: 3.0
**********************
Transcript started, output file is E:\tiny11\tiny11.log
Welcome to the tiny11 image creator! Release: 05-06-24
Found install.esd, converting to install.wim...
Index : 2
Name : Windows 11 Home N
Description : Windows 11 Home N
Size : 19,623,195,471 bytes

Index : 3
Name : Windows 11 Education
Description : Windows 11 Education
Size : 20,643,138,306 bytes

Index : 4
Name : Windows 11 Education N
Description : Windows 11 Education N
Size : 20,065,876,499 bytes

Index : 5
Name : Windows 11 Pro
Description : Windows 11 Pro
Size : 20,663,779,355 bytes

Index : 6
Name : Windows 11 Pro N
Description : Windows 11 Pro N
Size : 20,085,428,586 bytes

The operation completed successfully.

Converting install.esd to install.wim. This may take a while...

Copying Windows image...
Copy complete!
Getting image information:

Deployment Image Servicing and Management tool
Version: 10.0.26311.5000

Details for image : C:\tiny11\sources\install.wim

Index : 1
Name : Windows 11 Pro
Description : Windows 11 Pro
Size : 20,663,779,355 bytes

The operation completed successfully.
Mounting Windows image. This may take a while.

SUCCESS: The file (or folder): "C:\tiny11\sources\install.wim" now owned by user "WS2025\Administrator".
processed file: C:\tiny11\sources\install.wim
Successfully processed 1 files; Failed processing 0 files

Deployment Image Servicing and Management tool
Version: 10.0.26311.5000

Mounting image
[==========================100.0%==========================]
The operation completed successfully.
Default system UI language code: de-DE
Architecture: amd64
Mounting complete! Performing removal of applications...


















Removing Edge:
Removing OneDrive:
Removal complete!
Loading registry...
Bypassing system requirements(on the system image):
Disabling Sponsored Apps:
Enabling Local Accounts on OOBE:
Copy-Item: E:\tiny11\tiny11maker.ps1:220
Line |
 220 |  Copy-Item -Path "$PSScriptRoot\autounattend.xml" -Destination "$Scrat …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path 'E:\tiny11\autounattend.xml' because it does not exist.
Copy-Item: E:\tiny11\tiny11maker.ps1:220
Line |
 220 |  Copy-Item -Path "$PSScriptRoot\autounattend.xml" -Destination "$Scrat …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path 'E:\tiny11\autounattend.xml' because it does not exist.

Disabling Reserved Storage:
Disabling BitLocker Device Encryption
Disabling Chat icon:
Removing Edge related registries
Disabling OneDrive folder backup
Disabling Telemetry:
False
MethodInvocationException: E:\tiny11\tiny11maker.ps1:322
Line |
 322 |  $regKey = [Microsoft.Win32.Registry]::LocalMachine.OpenSubKey("zSOFTW …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "OpenSubKey" with "3" argument(s): "Requested registry access is not allowed."
MethodInvocationException: E:\tiny11\tiny11maker.ps1:322
Line |
 322 |  $regKey = [Microsoft.Win32.Registry]::LocalMachine.OpenSubKey("zSOFTW …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "OpenSubKey" with "3" argument(s): "Requested registry access is not allowed."

InvalidOperation: E:\tiny11\tiny11maker.ps1:323
Line |
 323 |  $regACL = $regKey.GetAccessControl()
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.
InvalidOperation: E:\tiny11\tiny11maker.ps1:323
Line |
 323 |  $regACL = $regKey.GetAccessControl()
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.

InvalidOperation: E:\tiny11\tiny11maker.ps1:324
Line |
 324 |  $regACL.SetOwner($adminGroup)
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.
InvalidOperation: E:\tiny11\tiny11maker.ps1:324
Line |
 324 |  $regACL.SetOwner($adminGroup)
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.

InvalidOperation: E:\tiny11\tiny11maker.ps1:325
Line |
 325 |  $regKey.SetAccessControl($regACL)
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.
InvalidOperation: E:\tiny11\tiny11maker.ps1:325
Line |
 325 |  $regKey.SetAccessControl($regACL)
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.

InvalidOperation: E:\tiny11\tiny11maker.ps1:326
Line |
 326 |  $regKey.Close()
     |  ~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.
InvalidOperation: E:\tiny11\tiny11maker.ps1:326
Line |
 326 |  $regKey.Close()
     |  ~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.

Owner changed to Administrators.
MethodInvocationException: E:\tiny11\tiny11maker.ps1:328
Line |
 328 |  $regKey = [Microsoft.Win32.Registry]::LocalMachine.OpenSubKey("zSOFTW …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "OpenSubKey" with "3" argument(s): "Requested registry access is not allowed."
MethodInvocationException: E:\tiny11\tiny11maker.ps1:328
Line |
 328 |  $regKey = [Microsoft.Win32.Registry]::LocalMachine.OpenSubKey("zSOFTW …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "OpenSubKey" with "3" argument(s): "Requested registry access is not allowed."

InvalidOperation: E:\tiny11\tiny11maker.ps1:329
Line |
 329 |  $regACL = $regKey.GetAccessControl()
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.
InvalidOperation: E:\tiny11\tiny11maker.ps1:329
Line |
 329 |  $regACL = $regKey.GetAccessControl()
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.

InvalidOperation: E:\tiny11\tiny11maker.ps1:331
Line |
 331 |  $regACL.SetAccessRule($regRule)
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.
InvalidOperation: E:\tiny11\tiny11maker.ps1:331
Line |
 331 |  $regACL.SetAccessRule($regRule)
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.

InvalidOperation: E:\tiny11\tiny11maker.ps1:332
Line |
 332 |  $regKey.SetAccessControl($regACL)
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.
InvalidOperation: E:\tiny11\tiny11maker.ps1:332
Line |
 332 |  $regKey.SetAccessControl($regACL)
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.

Permissions modified for Administrators group.
Registry key permissions successfully updated.
InvalidOperation: E:\tiny11\tiny11maker.ps1:335
Line |
 335 |  $regKey.Close()
     |  ~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.
InvalidOperation: E:\tiny11\tiny11maker.ps1:335
Line |
 335 |  $regKey.Close()
     |  ~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.

Deleting Application Compatibility Appraiser
Deleting Customer Experience Improvement Program
Deleting Program Data Updater
Deleting autochk proxy
Deleting QueueReporting
Tweaking complete!
Unmounting Registry...
InvalidOperation: E:\tiny11\tiny11maker.ps1:352
Line |
 352 |  $regKey.Close()
     |  ~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.
InvalidOperation: E:\tiny11\tiny11maker.ps1:352
Line |
 352 |  $regKey.Close()
     |  ~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.


Cleaning up image...
Cleanup complete.

Unmounting image...

Exporting image...

Windows image completed. Continuing with boot.wim.
Mounting boot image:
processed file: C:\tiny11\sources\boot.wim
Successfully processed 1 files; Failed processing 0 files

Deployment Image Servicing and Management tool
Version: 10.0.26311.5000

Mounting image
[==========================100.0%==========================]
The operation completed successfully.
Loading registry...
The operation completed successfully.
The operation completed successfully.
The operation completed successfully.
The operation completed successfully.
The operation completed successfully.
Bypassing system requirements(on the setup image):
Tweaking complete!
Unmounting Registry...
InvalidOperation: E:\tiny11\tiny11maker.ps1:398
Line |
 398 |  $regKey.Close()
     |  ~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.
InvalidOperation: E:\tiny11\tiny11maker.ps1:398
Line |
 398 |  $regKey.Close()
     |  ~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.

InvalidOperation: E:\tiny11\tiny11maker.ps1:404
Line |
 404 |  $regKey.Close()
     |  ~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.
InvalidOperation: E:\tiny11\tiny11maker.ps1:404
Line |
 404 |  $regKey.Close()
     |  ~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.


Unmounting image...

The tiny11 image is now completed. Proceeding with the making of the ISO...
Copying unattended file for bypassing MS account on OOBE...
Copy-Item: E:\tiny11\tiny11maker.ps1:412
Line |
 412 |  Copy-Item -Path "$PSScriptRoot\autounattend.xml" -Destination "$Scrat …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path 'E:\tiny11\autounattend.xml' because it does not exist.
Copy-Item: E:\tiny11\tiny11maker.ps1:412
Line |
 412 |  Copy-Item -Path "$PSScriptRoot\autounattend.xml" -Destination "$Scrat …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path 'E:\tiny11\autounattend.xml' because it does not exist.

Creating ISO image...
ADK folder not found. Will be using bundled oscdimg.exe.
Downloading oscdimg.exe...
oscdimg.exe downloaded successfully.

Scanning source tree (1000 files in 97 directories)
Scanning source tree complete (1057 files in 103 directories)

Computing directory information complete

Image file is 4448256000 bytes (before optimization)

Writing 1057 files in 103 directories to E:\tiny11\tiny11.iso

100% complete

Storage optimization saved 66 files, 15857664 bytes (1% of image)

After optimization, image file is 4434878464 bytes
Space saved because of embedding, sparseness or optimization = 15857664

Done.
Creation completed! Press any key to exit the script...
https://github.com/ntdevlabs/tiny11builder/issues/263
Performing Cleanup...
**********************
PowerShell transcript end
End time: 20241106223659
**********************

```

**Comment by Xenshen** [comment]
Same for me it keeps building and completing and tons of errors and when i use it to install. Nothing is removed everything still gets installed.

**Comment by Karl-WE** [comment]
Have a look at the revised Code in #263

You have to start it
Windows + X
 Terminal (Admin) console, PowerShell

.\tiny11.ps1 -scratchdrive c

**Comment by Xenshen** [comment]
Well I tried again and I’m getting same errors

**Comment by Xenshen** [comment]
[dism.log](https://github.com/user-attachments/files/17656318/dism.log)

Included the log

**Comment by ismenc** [comment]
I've got problems with 24H2. While installing it will crash at 10%.
How can we get a previous stable windows release from safe source?

**Comment by Xenshen** [comment]
Just got to windows website and download the iso it's the latest release.
Good question where you can get one older from a trusted source

**Comment by Karl-WE** [comment]
This is the only official source from Microsoft for home users
https://www.microsoft.com/software-download/windows11

**Comment by Karl-WE** [comment]
#268 has been merged into Main Branch.

With this, the errors mentioned should be resolved. Please Download the latest file. 

Please do not use context menu but execute the script from Microsoft Terminal PowerShell 5.1 / 7.x.

@Xenshen @spd-asia @doums

Hope that the issues are resolved.

**Comment by orzcode** [comment]
> #268 has been merged into Main Branch.
> 
> With this, the errors mentioned should be resolved. Please Download the latest file.
> 
> Please do not use context menu but execute the script from Microsoft Terminal PowerShell 5.1 / 7.x.
> 
> @Xenshen @spd-asia @doums
> 
> Hope that the issues are resolved. Please close if it's working or comment.

Thank you so much for your help. 

I am getting the same errors - "Requested registry access is not allowed" and similar "null value expression" errors despite following these instructions. Potentially the problem is with the Scratchdisk parameter.

You suggested:

**.\tinymaker11.ps1 -scratchdirectory yourdriveletter**

I tried several variations of:

**.\tiny11maker.ps1 -C:\Users\tiny\ C:**

and it flashes up a momentary error about the scratchdisk parameter being wrong, before continuing anyway and giving those errors.

If my parameters are the issue, can you please give me the _exact_ syntax?

I am using the latest 24H2 iso from Microsoft. I have attached the log file below:

`**********************
PowerShell transcript start
Start time: 20241212140208
Username: ORZDESKTOP\Orz
RunAs User: ORZDESKTOP\Orz
Configuration Name: 
Machine: ORZDESKTOP (Microsoft Windows NT 10.0.22631.0)
Host Application: C:\Program Files\PowerShell\7\pwsh.dll
Process ID: 284
PSVersion: 7.4.6
PSEdition: Core
GitCommitId: 7.4.6
OS: Microsoft Windows 10.0.22631
Platform: Win32NT
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1, 6.0, 7.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
WSManStackVersion: 3.0
**********************
Transcript started, output file is \tiny11.log
Welcome to the tiny11 image creator! Release: 05-06-24
Drive letter set to h:
Copying Windows image...
Copy complete!
Getting image information:

ImageIndex       : 1
ImageName        : Windows 11 Home
ImageDescription : Windows 11 Home
ImageSize        : 18,709,107,315 bytes

ImageIndex       : 2
ImageName        : Windows 11 Home N
ImageDescription : Windows 11 Home N
ImageSize        : 18,162,298,137 bytes

ImageIndex       : 3
ImageName        : Windows 11 Home Single Language
ImageDescription : Windows 11 Home Single Language
ImageSize        : 18,688,958,400 bytes

ImageIndex       : 4
ImageName        : Windows 11 Education
ImageDescription : Windows 11 Education
ImageSize        : 19,213,845,892 bytes

ImageIndex       : 5
ImageName        : Windows 11 Education N
ImageDescription : Windows 11 Education N
ImageSize        : 18,673,246,054 bytes

ImageIndex       : 6
ImageName        : Windows 11 Pro
ImageDescription : Windows 11 Pro
ImageSize        : 19,216,462,493 bytes

ImageIndex       : 7
ImageName        : Windows 11 Pro N
ImageDescription : Windows 11 Pro N
ImageSize        : 18,675,690,173 bytes

ImageIndex       : 8
ImageName        : Windows 11 Pro Education
ImageDescription : Windows 11 Pro Education
ImageSize        : 19,213,896,530 bytes

ImageIndex       : 9
ImageName        : Windows 11 Pro Education N
ImageDescription : Windows 11 Pro Education N
ImageSize        : 18,673,271,823 bytes

ImageIndex       : 10
ImageName        : Windows 11 Pro for Workstations
ImageDescription : Windows 11 Pro for Workstations
ImageSize        : 19,213,947,168 bytes

ImageIndex       : 11
ImageName        : Windows 11 Pro N for Workstations
ImageDescription : Windows 11 Pro N for Workstations
ImageSize        : 18,673,297,592 bytes

Mounting Windows image. This may take a while.



Path   : \scratchdir
Online : False

Default system UI language code: en-GB
Architecture: amd64
Mounting complete! Performing removal of applications...


















Removing Edge:
Removing OneDrive:
Removal complete!
Loading registry...
Bypassing system requirements(on the system image):
Disabling Sponsored Apps:
Enabling Local Accounts on OOBE:
Disabling Reserved Storage:
Disabling BitLocker Device Encryption
Disabling Chat icon:
Removing Edge related registries
Disabling OneDrive folder backup
Disabling Telemetry:
Prevents installation or DevHome and Outlook:
False
MethodInvocationException: C:\Users\tiny\tiny11maker.ps1:346
Line |
 346 |  $regKey = [Microsoft.Win32.Registry]::LocalMachine.OpenSubKey("zSOFTW …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "OpenSubKey" with "3" argument(s): "Requested registry access is not allowed."
MethodInvocationException: C:\Users\tiny\tiny11maker.ps1:346
Line |
 346 |  $regKey = [Microsoft.Win32.Registry]::LocalMachine.OpenSubKey("zSOFTW …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "OpenSubKey" with "3" argument(s): "Requested registry access is not allowed."

InvalidOperation: C:\Users\tiny\tiny11maker.ps1:347
Line |
 347 |  $regACL = $regKey.GetAccessControl()
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.
InvalidOperation: C:\Users\tiny\tiny11maker.ps1:347
Line |
 347 |  $regACL = $regKey.GetAccessControl()
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.

InvalidOperation: C:\Users\tiny\tiny11maker.ps1:348
Line |
 348 |  $regACL.SetOwner($adminGroup)
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.
InvalidOperation: C:\Users\tiny\tiny11maker.ps1:348
Line |
 348 |  $regACL.SetOwner($adminGroup)
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.

InvalidOperation: C:\Users\tiny\tiny11maker.ps1:349
Line |
 349 |  $regKey.SetAccessControl($regACL)
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.
InvalidOperation: C:\Users\tiny\tiny11maker.ps1:349
Line |
 349 |  $regKey.SetAccessControl($regACL)
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.

InvalidOperation: C:\Users\tiny\tiny11maker.ps1:350
Line |
 350 |  $regKey.Close()
     |  ~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.
InvalidOperation: C:\Users\tiny\tiny11maker.ps1:350
Line |
 350 |  $regKey.Close()
     |  ~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.

Owner changed to Administrators.
MethodInvocationException: C:\Users\tiny\tiny11maker.ps1:352
Line |
 352 |  $regKey = [Microsoft.Win32.Registry]::LocalMachine.OpenSubKey("zSOFTW …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "OpenSubKey" with "3" argument(s): "Requested registry access is not allowed."
MethodInvocationException: C:\Users\tiny\tiny11maker.ps1:352
Line |
 352 |  $regKey = [Microsoft.Win32.Registry]::LocalMachine.OpenSubKey("zSOFTW …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "OpenSubKey" with "3" argument(s): "Requested registry access is not allowed."

InvalidOperation: C:\Users\tiny\tiny11maker.ps1:353
Line |
 353 |  $regACL = $regKey.GetAccessControl()
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.
InvalidOperation: C:\Users\tiny\tiny11maker.ps1:353
Line |
 353 |  $regACL = $regKey.GetAccessControl()
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.

InvalidOperation: C:\Users\tiny\tiny11maker.ps1:355
Line |
 355 |  $regACL.SetAccessRule($regRule)
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.
InvalidOperation: C:\Users\tiny\tiny11maker.ps1:355
Line |
 355 |  $regACL.SetAccessRule($regRule)
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.

InvalidOperation: C:\Users\tiny\tiny11maker.ps1:356
Line |
 356 |  $regKey.SetAccessControl($regACL)
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.
InvalidOperation: C:\Users\tiny\tiny11maker.ps1:356
Line |
 356 |  $regKey.SetAccessControl($regACL)
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.

Permissions modified for Administrators group.
Registry key permissions successfully updated.
InvalidOperation: C:\Users\tiny\tiny11maker.ps1:359
Line |
 359 |  $regKey.Close()
     |  ~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.
InvalidOperation: C:\Users\tiny\tiny11maker.ps1:359
Line |
 359 |  $regKey.Close()
     |  ~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.

Deleting Application Compatibility Appraiser
Deleting Customer Experience Improvement Program
Deleting Program Data Updater
Deleting autochk proxy
Deleting QueueReporting
Tweaking complete!
Unmounting Registry...
InvalidOperation: C:\Users\tiny\tiny11maker.ps1:376
Line |
 376 |  $regKey.Close()
     |  ~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.
InvalidOperation: C:\Users\tiny\tiny11maker.ps1:376
Line |
 376 |  $regKey.Close()
     |  ~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.


Cleaning up image...

ImageHealthState : Healthy

Cleanup complete.

Unmounting image...

LogPath          : C:\Windows\Logs\DISM\dism.log
ScratchDirectory : 
LogLevel         : WarningsInfo

Exporting image...

ImagePath        : \tiny11\sources\install2.wim
Name             : 
LogPath          : C:\Windows\Logs\DISM\dism.log
ScratchDirectory : C:\Windows\temp\
LogLevel         : WarningsInfo

Windows image completed. Continuing with boot.wim.
Mounting boot image:
processed file: \tiny11\sources\boot.wim
Successfully processed 1 files; Failed processing 0 files

Path   : \scratchdir
Online : False

Loading registry...
The operation completed successfully.
The operation completed successfully.
The operation completed successfully.
The operation completed successfully.
The operation completed successfully.
Bypassing system requirements(on the setup image):
Tweaking complete!
Unmounting Registry...
InvalidOperation: C:\Users\tiny\tiny11maker.ps1:423
Line |
 423 |  $regKey.Close()
     |  ~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.
InvalidOperation: C:\Users\tiny\tiny11maker.ps1:423
Line |
 423 |  $regKey.Close()
     |  ~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.

InvalidOperation: C:\Users\tiny\tiny11maker.ps1:429
Line |
 429 |  $regKey.Close()
     |  ~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.
InvalidOperation: C:\Users\tiny\tiny11maker.ps1:429
Line |
 429 |  $regKey.Close()
     |  ~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.

The operation completed successfully.
Unmounting image...

LogPath          : C:\Windows\Logs\DISM\dism.log
ScratchDirectory : 
LogLevel         : WarningsInfo

The tiny11 image is now completed. Proceeding with the making of the ISO...
Copying unattended file for bypassing MS account on OOBE...
Creating ISO image...
ADK folder not found. Will be using bundled oscdimg.exe.
oscdimg.exe already exists locally.

OSCDIMG 2.56 CD-ROM and DVD-ROM Premastering Utility
Copyright (C) Microsoft, 1993-2012. All rights reserved.
Licensed only for producing Microsoft authorized content.


Scanning source tree (1000 files in 97 directories)
Scanning source tree complete (1057 files in 103 directories)

Computing directory information complete

Image file is 5644025856 bytes (before optimization)

Writing 1057 files in 103 directories to C:\Users\tiny\tiny11.iso

100% complete

Storage optimization saved 66 files, 15710208 bytes (1% of image)

After optimization, image file is 5630803968 bytes
Space saved because of embedding, sparseness or optimization = 15710208

Done.
Creation completed! Press any key to exit the script...

Performing Cleanup...
**********************
PowerShell transcript end
End time: 20241212141149
**********************
`

**Comment by orzcode** [comment]
> #268 has been merged into Main Branch.
> 
> With this, the errors mentioned should be resolved. Please Download the latest file.
> 
> Please do not use context menu but execute the script from Microsoft Terminal PowerShell 5.1 / 7.x.
> 
> @Xenshen @spd-asia @doums
> 
> Hope that the issues are resolved. Please close if it's working or comment.

Alright, I figured out what you meant with the syntax - 

I believe you meant **.\tinymaker11.ps1 -ScratchDisk _yourdriveletter_**

Anyway, I tried this - but still get those numerous registry errors.

To confirm, this should still be working with 24H2 Pro, right? Which is what I'm using.

**Comment by Karl-WE** [comment]
I will try to invest more time on helping with this issue.
I understand tinyw11 got a lot of push also in tech media.

However I really would focus on the feature PRs before fiddling on testing scratchdirectory to other location.

I needs complete different logic.

Please free up space on C if you need it. 

If there's space on C do not pass any parameter. 

Otherwise could provide an Image to share on OneDrive.
