### ISSUE TITLE
tiny11coremaker not working, any official word?

### ISSUE THREAD

**Issue by Courtjustcourt** [ntdevlabs/tiny11builder#267]
Been running everything as instructed and constantly getting a %10 windows error with Core. Does anyone have any answers on why or whats going on with it? I've checked on here with no answers. Does anyone at least have a operable ISO of it to share?

**Comment by karagir** [comment]
Almost same results here. With W11IoT24H2 and tiny11Coremaker, the ISO is created, installation starts and when file copying reaches 5%, there is a pop-up which says windows 11 installation failed. Tried creating an image several times and every time its the same error consistently.
Kindly look into it. Thanks!!

**Comment by zyl-hub** [comment]
I got the same results here.

**Comment by ntdevlabs** [comment]
The issue is with the modern Windows installer requiring WinRE.wim to be included in the image. If you use the legacy installer it should work fine.

**Comment by Courtjustcourt** [comment]
> The issue is with the modern Windows installer requiring WinRE.wim to be included in the image. If you use the legacy installer it should work fine.

Appreciate the response. I'm still new to this, is their a way to get the legacy installer? Is it a swap of the WinRE.wim file or something similar?

**Comment by Courtjustcourt** [comment]
Still failing at 10%. @zyl-hub @karagir did you get it to work? If you did, what did you do?

**Comment by ntdevlabs** [comment]
Should be fixed now. Let me know how it goes!

**Comment by Courtjustcourt** [comment]
It still fails at exactly 10%, but everything else before that went much smoother and seemed faster.

**Comment by ntdevlabs** [comment]
Does it boot with the new installer (introduced in 24H2) or the old (Vista-like) one?

**Comment by Courtjustcourt** [comment]
Boots with the new installer and even boots on a really old system I have. Previous one wouldn't boot on that system without giving the error saying its not qualified.

**Comment by Courtjustcourt** [comment]
Managed to get tiny11 core "Windows Pro" version to install without getting 10% error. Not sure why during install it's running windows update though. should I be disconnecting Internet?

![17318821423974382246842837168066](https://github.com/user-attachments/assets/02131599-4cd2-47c0-943b-124287d84687)

**Comment by Courtjustcourt** [comment]
Now tiny11 core works. Thanks for putting in the time and effort to fix & get it up and running. Much appreciated!

**Comment by lucientergal** [comment]
nothing works with 24h2 images...
